name: weather_forcasting
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: "2.2.3"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0

  ## Architecture
  flutter_bloc: ^7.2.0
  provider: ^6.0.2

  ## Persistence
  shared_preferences: ^2.0.7
  flutter_secure_storage: ^4.2.1

  ## API, JSON, and Models
  dio: ^4.0.0
  retrofit: ^2.0.1
  freezed_annotation: ^0.14.2
  json_serializable: ^4.1.4

  ## UI and Animations
  carousel_slider: any
  flutter_svg: ^0.22.0
  flutter_screenutil: ^5.0.0+2
  cached_network_image: ^3.1.0

  ## Testing and Development
  alice_lightweight: ^3.0.0
  shake: ^1.0.1
  dio_http_formatter: ^2.0.0
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.2
  flutter_gen_runner: ^3.0.2
  freezed: ^0.14.2
  retrofit_generator: ^2.0.1

  dependency_validator:
  dart_code_metrics:
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_gen:
  output: lib/generated/
  lineLength: 80
  integrations:
    flutter_svg: true
    